Name: nemo-qml-plugin-configuration
Summary: Configuration plugin for Nemo Mobile
URL: https://github.com/nemomobile/nemo-qml-plugin-configuration
Group: System/Libraries
Description: "%{summary}."
Version: 0.0.0
Release: 1
Sources:
    - "%{name}-%{version}.tar.bz2"
License: BSD
Configure: none
Builder: qmake
PkgConfigBR:
    - QtCore >= 4.7.0
    - QtDeclarative
    - mlite
Provides:
    - nemo-qml-plugins-configuration > 0.3.13
Obsoletes:
    - nemo-qml-plugins-configuration <= 0.3.13
Files:
    - "%{_libdir}/qt4/imports/org/nemomobile/configuration/libnemoconfiguration.so"
    - "%{_libdir}/qt4/imports/org/nemomobile/configuration/qmldir"
